apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
        - name: kafka-broker
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "4"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-controller:9093
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          ports:
            - containerPort: 19092
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
spec:
  selector:
    app: kafka-broker-1
  ports:
    - name: broker-internal
      port: 19092
      targetPort: 19092
    - name: broker-host
      port: 29092
      targetPort: 9092
