apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-controller
  template:
    metadata:
      labels:
        app: kafka-controller
    spec:
      containers:
        - name: kafka-controller
          image: apache/kafka:latest
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: CONTROLLER://0.0.0.0:9093
            - name: KAFKA_PROCESS_ROLES
              value: controller
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-controller:9093"
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_NODE_ID
              value: "1"
          ports:
            - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller
spec:
  selector:
    app: kafka-controller
  ports:
    - port: 9093
      targetPort: 9093