apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "1"  # Setze die Node ID auf 1 für diesen Broker
            - name: KAFKA_PROCESS_ROLES
              value: "broker"  # Nur als Broker
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:19092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:19092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          ports:
            - containerPort: 19092
            - containerPort: 9092