apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfr-consumer
  template:
    metadata:
      labels:
        app: sfr-consumer
    spec:
      containers:
        - name: sfr-consumer
          image: sfr-app
          env:
            - name: KAFKA_BOOTSTRAP
              value: "broker-1:19092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Database=ClothingAd;Username=postgres;Password=mysecret"
          ports:
            - containerPort: 80