apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfr-consumer
  template:
    metadata:
      labels:
        app: sfr-consumer
    spec:
      containers:
        - name: sfr-consumer
          image: sfr-consumer:dev # ← das hier!
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka:29092
            - name: SCHEMA_REGISTRY_URL
              value: http://host.docker.internal:8081
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Database=ClothingAd;Username=postgres;Password=mysecret