apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfr-producer
  template:
    metadata:
      labels:
        app: sfr-producer
    spec:
      containers:
        - name: sfr-producer
          image: sfr-app
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka-broker:19092
            - name: SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
          command: [ "producer" ]
          ports:
            - containerPort: 8080